// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Les migrations Prisma necessitent une connexion non poolee.
  // DIRECT_URL pointe sur l'endpoint Neon direct (sans -pooler).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
